# Generated by Django 4.1.3 on 2022-12-05 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('03688dc8-53c5-4dbd-be41-a1103099ba33'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singers', models.ManyToManyField(blank=True, to='singer.singer')),
            ],
        ),
    ]
